# Generated by Django 4.2.4 on 2023-09-21 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserInputs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('blood_group', models.CharField(max_length=10)),
                ('work_condition', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('image', models.ImageField(upload_to='user_inputs')),
                ('disease', models.JSONField(blank=True, null=True)),
                ('probability', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
