# Generated by Django 4.1.7 on 2023-09-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_userinputs_phone_number_userinputs_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinputs',
            name='disease',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userinputs',
            name='probability',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
